spring.application.name=demo

# Logging for debugging federation gateway issues
logging.level.com.netflix.graphql.dgs=DEBUG

server.port = 8088

#spring.datasource.url=jdbc:postgresql://172.210.73.43:5432/stock_tran_service?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=farmernew2024
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/pos-app?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=myuser
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway Configuration
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.validate-on-migrate=true
#spring.jpa.hibernate.ddl-auto=validate

spring.jpa.generate-ddl=false
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#services.farmer-config-service-base-url=http://localhost:8081/api/graphql