name: workflow-test.yml
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
